name = "Salon"
license = "MIT"
licenselink = "https://github.com/pori/hernandezand.co/blob/main/theme/salon/LICENSE"
description = "A place to hang up your artwork."
homepage = "https://hernandezand.co"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Alice Hernandez"
  homepage = "https://pori.codes"
